import { Helmet } from 'react-helmet';
import { useTranslation } from 'react-i18next';
import { HelpCircle } from 'lucide-react';
import {
  Accordion,
  AccordionContent,
  AccordionItem,
  AccordionTrigger,
} from "@/components/ui/accordion";

const FAQPage = () => {
  const { t } = useTranslation();

  // FAQ data
  const faqs = [
    {
      question: "What is solar energy?",
      answer: "Solar energy is power generated by harnessing the sun's radiation. It's a renewable, clean source of energy that can be converted into electricity through solar panels, which contain photovoltaic cells."
    },
    {
      question: "How do solar panels work?",
      answer: "Solar panels consist of photovoltaic cells that convert sunlight into electricity. When sunlight hits the panels, it creates an electric field across the layers, causing electricity to flow. This direct current (DC) electricity is then converted to alternating current (AC) by an inverter to power your home or business."
    },
    {
      question: "What are the benefits of solar energy?",
      answer: "Solar energy offers numerous benefits: it reduces electricity bills, provides a clean, renewable energy source, requires minimal maintenance, increases property value, and contributes to energy independence. In Saudi Arabia, it also aligns with the national vision for sustainable development."
    },
    {
      question: "Is my property suitable for solar panels?",
      answer: "Most properties in Saudi Arabia are ideal for solar installation due to the abundant sunshine. Factors to consider include: the size, angle, and orientation of your roof; whether there's significant shading; structural considerations; and local regulations. Our technicians can perform an assessment to determine the best solution for your specific needs."
    },
    {
      question: "How much does a solar system cost?",
      answer: "The cost varies depending on system size, property type, and specific requirements. However, with decreasing solar technology costs and the long-term energy savings, solar installations are increasingly affordable. Our service connects you with technicians who can provide detailed quotes based on your needs."
    },
    {
      question: "How long does the installation process take?",
      answer: "The timeline varies based on the system size and complexity. A typical residential installation can take 1-3 days for the physical installation, plus additional time for permit approvals and inspections. Commercial installations are generally larger and may take longer."
    },
    {
      question: "Do solar panels work during cloudy days or at night?",
      answer: "Solar panels generate less electricity during cloudy days and none at night. However, many solar systems include battery storage that allows you to store excess energy produced during sunny periods for use when production is low. Grid-connected systems also allow you to draw from the conventional power grid when needed."
    },
    {
      question: "How do I maintain solar panels?",
      answer: "Solar panels generally require minimal maintenance. In Saudi Arabia's climate, occasional cleaning to remove dust and sand is recommended to maintain optimal efficiency. Most manufacturers recommend professional cleaning 2-4 times per year. Our platform can connect you with maintenance technicians who provide this service."
    },
    {
      question: "What happens during a power outage?",
      answer: "Standard grid-tied solar systems will shut down during a power outage for safety reasons. However, systems with battery backup or special inverters can continue to provide electricity to your property during outages. Discuss your needs with a technician to determine the best setup for your situation."
    },
    {
      question: "How can I become a certified technician on Shamsak?",
      answer: "We welcome qualified solar technicians to our platform. To join, you'll need to register an account, provide proof of your certifications and experience, and complete our verification process. Once approved, you can create a profile showcasing your skills and services to potential clients."
    }
  ];

  return (
    <>
      <Helmet>
        <title>{t('footer.faq')} | {t('common.appName')}</title>
        <meta 
          name="description" 
          content="Frequently asked questions about solar energy, installation, and services provided through Shamsak" 
        />
      </Helmet>

      <div className="bg-neutral-100 py-16 fade-in">
        <div className="container mx-auto px-4">
          <div className="max-w-3xl mx-auto">
            <div className="text-center mb-12">
              <div className="flex items-center justify-center mb-4">
                <HelpCircle className="h-12 w-12 text-primary" />
              </div>
              <h1 className="text-3xl lg:text-4xl font-bold text-neutral-800 mb-4">
                {t('footer.faq')}
              </h1>
              <p className="text-lg text-neutral-700">
                Find answers to the most common questions about solar energy and our services
              </p>
            </div>

            <div className="bg-white p-6 rounded-lg shadow-md">
              <Accordion type="single" collapsible className="w-full">
                {faqs.map((faq, index) => (
                  <AccordionItem key={index} value={`item-${index}`}>
                    <AccordionTrigger className="text-left font-semibold text-neutral-800">
                      {faq.question}
                    </AccordionTrigger>
                    <AccordionContent className="text-neutral-700">
                      {faq.answer}
                    </AccordionContent>
                  </AccordionItem>
                ))}
              </Accordion>
            </div>

            <div className="mt-12 text-center">
              <h2 className="text-2xl font-bold text-neutral-800 mb-4">Still have questions?</h2>
              <p className="text-neutral-700 mb-6">
                If you couldn't find the answers you're looking for, please contact our team for assistance.
              </p>
              <a 
                href="/contact" 
                className="bg-primary text-white px-6 py-3 rounded-md font-medium hover:bg-opacity-90 transition-colors"
              >
                Contact Us
              </a>
            </div>
          </div>
        </div>
      </div>
    </>
  );
};

export default FAQPage;